AWSTemplateFormatVersion: 2010-09-09
Description: Setup peering between the Client VPC and the Management VPC

Parameters:
  VPCStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the VPC networking
      resources.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: vpc
  EnvName:
    Description: 'Client Name to tag resources with'  
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z]*'
    ConstraintDescription: any alphabetic string (1-16) characters in length
    
  ManagementVPCID:
    Description: Enter VPC ID of the Management VPC 
    Type: String 
    Default: vpc-0197f8392780d91a8
  
  ManagementVPCCIDR:
    Description: Enter Management VPC CIDR block.
    Type: String
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Default: 10.100.0.0/16
    ConstraintDescription: >-
      must be an IPv4 dotted quad plus slash plus network bit length in CIDR
      format

  #ManagementPrivateARouteTableID:
    #Description: >- 
      #Enter ID of the Management Private A route table. Copy/Paste from Outputs in the Cloudformation Section, 
        #in the Management Console!   
    #Type: String
    #Default: rtb-0d464f01707a931fb	
    
  #ManagementPrivateBRouteTableID:
    #Description: >- 
      #Enter ID of the Management Private B route table. Copy/Paste from Outputs in the Cloudformation Section, 
        #in the Management Console!   
    #Type: String
    #Default: rtb-0da00c2f4a452fe81
  #ManagementPublicARouteTableID:
    #Description: >- 
      #Enter ID of the Management Public A route table. Copy/Paste from Outputs in the Cloudformation Section, 
        #in the Management Console!   
    #Type: String
  #Default: rtb-0da00c2f4a452fe81
  #ManagementPublicBRouteTableID:
    #Description: >- 
      #Enter ID of the Management Public B route table. Copy/Paste from Outputs in the Cloudformation Section, 
        #in the Management Console!   
    #Type: String
  #Default: rtb-0da00c2f4a452fe81
  ManagementAccountID:
    Description: >- 
      Enter the 12 digit ID of the AWS Management Account. Tip Top right hand corner, Go to the Support Page.  
        Account number is displayed there 
    Type: Number
   
  ManagementVPCRegion:
    Description: Enter Region where Management VPC was created. Should be AWS Region format ie. us-east-2 etc
    Type: String 
    Default: us-east-2

  ManagementIAMRoleArn: 
    Description: Copy/Paste the Role ARN from IAM section in the Management Console for Cross Account Access.
    Type: String 
    
Resources: 
  
  VPCPeeringConnectionToManagement:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !ImportValue 
        'Fn::Sub': '${VPCStackName}-VpcId'
      PeerVpcId: !Ref ManagementVPCID
      PeerOwnerId: !Ref ManagementAccountID 
      PeerRegion: !Ref ManagementVPCRegion 
      PeerRoleArn: !Ref ManagementIAMRoleArn
      Tags:
        - Key: Name 
          Value: !Join
            - '-'
            - - !Ref EnvName
              - 'to Management VPC'  

  PeeringPublicARouteToManagementVPC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref ManagementVPCCIDR # VPC CIDR of the Management VPC
      RouteTableId: !ImportValue 
        'Fn::Sub': '${VPCStackName}-RouteTableAPublic'
      VpcPeeringConnectionId:
        Ref: VPCPeeringConnectionToManagement

  PeeringPublicBRouteToManagementVPC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref ManagementVPCCIDR # VPC CIDR of the Management VPC
      RouteTableId: !ImportValue 
        'Fn::Sub': '${VPCStackName}-RouteTableBPublic'
      VpcPeeringConnectionId:
        Ref: VPCPeeringConnectionToManagement

  PeeringPrivateARouteToManagementVPC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref ManagementVPCCIDR # VPC CIDR of the Management VPC
      RouteTableId: !ImportValue 
        'Fn::Sub': '${VPCStackName}-RouteTableAPrivate'
      VpcPeeringConnectionId:
        Ref: VPCPeeringConnectionToManagement

  PeeringPrivateBRouteToManagementVPC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref ManagementVPCCIDR # VPC CIDR of the Management VPC
      RouteTableId: !ImportValue 
        'Fn::Sub': '${VPCStackName}-RouteTableBPrivate'
      VpcPeeringConnectionId:
        Ref: VPCPeeringConnectionToManagement

  #ReversePublicARoutingTableEntry:
    #Type: AWS::EC2::Route
    #Properties:
      #RouteTableId: !Ref ManagementPublicARouteTableID
      #DestinationCidrBlock: '10.12.0.0/16' #!ImportValue 
        #'Fn::Sub': '${VPCStackName}-CidrBlock'
      #VpcPeeringConnectionId: !Ref VPCPeeringConnectionToManagement
  
  #ReversePublicBRoutingTableEntry:
    #Type: AWS::EC2::Route
    #DependsOn:
      #- PeeringConnection
    #Properties:
      #RouteTableId: !Ref ManagementPublicBRouteTableID
      #DestinationCidrBlock: !ImportValue 
        #'Fn::Sub': '${VPCStackName}-CidrBlock'
      #VpcPeeringConnectionId:
        #Ref: VPCPeeringConnectionToManagement

  #ReversePrivateARoutingTableEntry:
    #Type: AWS::EC2::Route
    #DependsOn:
      #- PeeringConnection
    #Properties:
      #RouteTableId: !Ref ManagementPrivateARouteTableID
      #DestinationCidrBlock: 10.12.0.0/16 #!ImportValue 
        #'Fn::Sub': '${VPCStackName}-CidrBlock'
      #VpcPeeringConnectionId:
        #Ref: VPCPeeringConnectionToManagement

  #ReversePrivateBRoutingTableEntry:
    #Type: AWS::EC2::Route
    #DependsOn:
      #- PeeringConnection
    #Properties:
      #RouteTableId: !Ref ManagementPrivateBRouteTableID
      #DestinationCidrBlock: !ImportValue 
        #'Fn::Sub': '${VPCStackName}-CidrBlock'
      #VpcPeeringConnectionId:
        #Ref: VPCPeeringConnectionToManagement
